package es.us.dp1.l4_01_25_26.petris.statistic;

public enum Metric {
    GAMES_PLAYED, VICTORIES, TOTAL_PLAY_TIME, GAMES_AS_PURPLE, GAMES_AS_GREEN, VICTORIES_AS_PURPLE, VICTORIES_AS_GREEN, MAX_BACTERY_PLAYED, MAX_SARCINE_PLAYED, MAX_TURNS_PLAYED;
}
